{% set name = "py7zr" %}
{% set version = "0.20.5" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 6fb4889c0fa32581818a3366984083253585d6c794e82c3242b8a12d6aeaabd3

build:
  number: 0
  entry_points:
    - py7zr = py7zr.__main__:main
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - pip
    - python
    - setuptools
    - setuptools-scm 7.0.4
    - wheel
  run:
    - brotli-python >=1.0.9
    - importlib-metadata  # [py<38]
    - inflate64 >=0.3.1
    - multivolumefile >=0.2.3
    - psutil
    - pybcj >=0.6.0
    - pycryptodomex >=3.6.6
    - pyppmd >=0.18.1,<1.1.0
    - python
    - pyzstd >=0.14.4
    - texttable

test:
  imports:
    - py7zr
  commands:
    - pip check
    - py7zr --help
  requires:
    - pip

about:
  description: |
    py7zr is a library and utility to support 7zip archive compression, decompression,
    encryption and decryption written by Python programming language.
  home: https://github.com/miurahr/py7zr
  dev_url: https://github.com/miurahr/py7zr
  doc_url: https://github.com/miurahr/py7zr#readme
  summary: Pure python 7-zip library
  license: LGPL-2.1-or-later
  license_family: LGPL
  license_file: LICENSE

extra:
  recipe-maintainers:
    - sarthakpati
